f=open("gate0_crypto.h","r")
c=f.read()
f.close()
c=c.replace("#endif\n","")
f=open("gate0_crypto.h","w")
f.write(c)
f.write("#define GATE0_ED25519_PUBKEY_BYTES 32\n")
f.write("#define GATE0_ED25519_PRIVKEY_BYTES 64\n")
f.write("#define GATE0_X25519_KEY_BYTES 32\n")
f.write("typedef enum {\n")
f.write("GATE0_OK=0,\n")
f.write("GATE0_ERR_VERIFY=-1,\n")
f.write("GATE0_ERR_DECRYPT=-2,\n")
f.write("GATE0_ERR_NONCE_REUSE=-3,\n")
f.write("GATE0_ERR_BADKEY=-4,\n")
f.write("GATE0_ERR_REPLAY=-7,\n")
f.write("GATE0_ERR_CAPABILITY=-8,\n")
f.write("GATE0_ERR_CHAIN=-9,\n")
f.write("} gate0_status_t;\n")
f.write("#endif\n")
f.close()
