f=open("gate0_crypto.h","r")
c=f.read()
f.close()
c=c.replace("#endif\n","")
f=open("gate0_crypto.h","w")
f.write(c)
f.write("gate0_status_t gate0_ed25519_keygen(gate0_ed25519_keypair_t *kp);\n")
f.write("gate0_status_t gate0_ed25519_sign(const gate0_ed25519_keypair_t *kp,const uint8_t *msg,size_t len,uint8_t sig[64]);\n")
f.write("gate0_status_t gate0_ed25519_verify(const uint8_t pub[32],const uint8_t *msg,size_t len,const uint8_t sig[64]);\n")
f.write("gate0_status_t gate0_x25519_keygen(gate0_x25519_keypair_t *kp);\n")
f.write("gate0_status_t gate0_x25519_dh(const gate0_x25519_keypair_t *local,const uint8_t remote[32],uint8_t secret[32]);\n")
f.write("gate0_status_t gate0_aead_init(gate0_aead_ctx_t *ctx,const uint8_t key[32]);\n")
f.write("gate0_status_t gate0_aead_encrypt(gate0_aead_ctx_t *ctx,const uint8_t *pt,size_t pt_len,uint8_t *ct,uint8_t tag[16],uint8_t nonce[12]);\n")
f.write("gate0_status_t gate0_aead_decrypt(gate0_aead_ctx_t *ctx,const uint8_t *ct,size_t ct_len,const uint8_t tag[16],const uint8_t nonce[12],uint8_t *pt);\n")
f.write("gate0_status_t gate0_sha256(const uint8_t *data,size_t len,uint8_t digest[32]);\n")
f.write("gate0_status_t gate0_chain_init(gate0_chain_link_t *link,const uint8_t *entry,size_t len);\n")
f.write("gate0_status_t gate0_chain_append(gate0_chain_link_t *prev,gate0_chain_link_t *next,const uint8_t *entry,size_t len);\n")
f.write("gate0_status_t gate0_chain_verify(const gate0_chain_link_t *prev,const gate0_chain_link_t *next);\n")
f.write("#endif\n")
f.close()
