#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#define MAX_SENDERS 32
#define MAX_NONCES 256
#define NONCE_SIZE 16
#define MAX_TESTS 100000
#define CLOCK_SKEW_NS UINT64_C(5000000000)
typedef enum{AUTH_OBSERVER=0,AUTH_OPERATOR=1,AUTH_ADMIN=2,AUTH_EMERGENCY=3}Authority;
typedef enum{CMD_TELEMETRY_ENABLE=0x01,CMD_SETPOINT=0x02,CMD_ENTER_SAFE_STATE=0x03,CMD_QUERY_STATUS=0x04,CMD_CONFIG_PARAM=0x05,CMD_ACK_ALARM=0x06,CMD_ESTOP_BYPASS=0xF0,CMD_OVERSPEED_BYPASS=0xF1,CMD_OVERTEMP_BYPASS=0xF2,CMD_OVERVOLT_BYPASS=0xF3,CMD_SENSOR_SUPPRESS=0xF4,CMD_SAFETY_DISABLE=0xF5,CMD_FORCE_EXECUTE=0xF6,CMD_IGNORE_INTERLOCK=0xF7}CommandType;
typedef enum{GATE_ACCEPT=0x0000,GATE_UNKNOWN_SENDER=0x0101,GATE_BOOTSTRAP_INVALID=0x0102,GATE_EXPIRED=0x0201,GATE_FUTURE_TIMESTAMP=0x0202,GATE_NONCE_REPLAY=0x0301,GATE_SEQUENCE_REPLAY=0x0401,GATE_SEQUENCE_GAP=0x0402,GATE_WRONG_NODE=0x0501,GATE_AUTHORITY_INSUFFICIENT=0x0601,GATE_COMMAND_BLOCKED=0x0701,GATE_INTERLOCK_UNSAFE=0x0801,GATE_PAYLOAD_CORRUPT=0x0901}GateResult;
typedef struct{uint32_t sender_id;uint32_t node_id;uint64_t sequence;uint64_t issued_at_ns;uint64_t expires_at_ns;uint8_t nonce[NONCE_SIZE];uint8_t command_type;Authority sender_authority;Authority required_authority;uint32_t payload_hash_expected;uint32_t payload_hash_actual;}Command;
typedef struct{int used;uint32_t sender_id;uint32_t allowed_node;uint64_t current_seq;Authority authority;}SenderState;
typedef struct{int estop;int overspeed;int overtemp;int overvoltage;}Interlocks;
typedef struct{SenderState senders[MAX_SENDERS];uint8_t nonces[MAX_NONCES][NONCE_SIZE];size_t nonce_count;Interlocks interlocks;}Gate;
static uint64_t rng_state=UINT64_C(0xC0FFEE123456789A);
static uint64_t rng_next(void){uint64_t x=rng_state;x^=x<<13;x^=x>>7;x^=x<<17;rng_state=x;return x;}
static void make_nonce(uint8_t nonce[NONCE_SIZE]){size_t i;for(i=0;i<NONCE_SIZE;++i)nonce[i]=(uint8_t)(rng_next()&0xFF);}
static int nonce_equal(const uint8_t a[NONCE_SIZE],const uint8_t b[NONCE_SIZE]){return memcmp(a,b,NONCE_SIZE)==0;}
static int nonce_seen(const Gate*gate,const uint8_t nonce[NONCE_SIZE]){size_t i;for(i=0;i<gate->nonce_count;++i)if(nonce_equal(gate->nonces[i],nonce))return 1;return 0;}
static void nonce_record(Gate*gate,const uint8_t nonce[NONCE_SIZE]){if(gate->nonce_count<MAX_NONCES){memcpy(gate->nonces[gate->nonce_count],nonce,NONCE_SIZE);gate->nonce_count++;return;}memmove(gate->nonces,gate->nonces+1,(MAX_NONCES-1)*NONCE_SIZE);memcpy(gate->nonces[MAX_NONCES-1],nonce,NONCE_SIZE);}
static SenderState*find_sender(Gate*gate,uint32_t sender_id){size_t i;for(i=0;i<MAX_SENDERS;++i)if(gate->senders[i].used&&gate->senders[i].sender_id==sender_id)return&gate->senders[i];return NULL;}
static SenderState*bootstrap_sender(Gate*gate,const Command*cmd){size_t i;for(i=0;i<MAX_SENDERS;++i)if(!gate->senders[i].used){SenderState*s=&gate->senders[i];memset(s,0,sizeof(*s));s->used=1;s->sender_id=cmd->sender_id;s->allowed_node=cmd->node_id;s->current_seq=1;s->authority=cmd->sender_authority;return s;}return NULL;}
static int command_is_blocked(uint8_t t){return t>=CMD_ESTOP_BYPASS&&t<=CMD_IGNORE_INTERLOCK;}
static int interlocks_safe(const Gate*gate,uint8_t t){if(t==CMD_ENTER_SAFE_STATE)return 1;if(gate->interlocks.estop)return 0;if(gate->interlocks.overspeed)return 0;if(gate->interlocks.overtemp)return 0;if(gate->interlocks.overvoltage)return 0;return 1;}
static GateResult gate_evaluate(Gate*gate,const Command*cmd,uint64_t now_ns){SenderState*sender;if(cmd->payload_hash_expected!=cmd->payload_hash_actual)return GATE_PAYLOAD_CORRUPT;if(cmd->expires_at_ns<now_ns)return GATE_EXPIRED;if(cmd->issued_at_ns>now_ns+CLOCK_SKEW_NS)return GATE_FUTURE_TIMESTAMP;if(command_is_blocked(cmd->command_type))return GATE_COMMAND_BLOCKED;if(!interlocks_safe(gate,cmd->command_type))return GATE_INTERLOCK_UNSAFE;if(nonce_seen(gate,cmd->nonce))return GATE_NONCE_REPLAY;sender=find_sender(gate,cmd->sender_id);if(sender==NULL){if(cmd->sequence!=1)return GATE_BOOTSTRAP_INVALID;sender=bootstrap_sender(gate,cmd);if(sender==NULL)return GATE_UNKNOWN_SENDER;nonce_record(gate,cmd->nonce);return GATE_ACCEPT;}if(cmd->node_id!=sender->allowed_node)return GATE_WRONG_NODE;if(sender->authority<cmd->required_authority)return GATE_AUTHORITY_INSUFFICIENT;if(cmd->sequence<=sender->current_seq)return GATE_SEQUENCE_REPLAY;if(cmd->sequence>sender->current_seq+1)return GATE_SEQUENCE_GAP;sender->current_seq=cmd->sequence;nonce_record(gate,cmd->nonce);return GATE_ACCEPT;}
static unsigned tests_run=0,tests_passed=0;
static void expect(const char*name,GateResult actual,GateResult expected){tests_run++;if(actual==expected){tests_passed++;printf("[PASS] %-35s result=0x%04X\n",name,actual);return;}printf("[FAIL] %-35s expected=0x%04X actual=0x%04X\n",name,expected,actual);}
static Command command_make(uint32_t sender,uint32_t node,uint64_t seq,uint64_t now){Command cmd;memset(&cmd,0,sizeof(cmd));cmd.sender_id=sender;cmd.node_id=node;cmd.sequence=seq;cmd.issued_at_ns=now;cmd.expires_at_ns=now+UINT64_C(10000000000);cmd.command_type=CMD_SETPOINT;cmd.sender_authority=AUTH_ADMIN;cmd.required_authority=AUTH_OPERATOR;cmd.payload_hash_expected=UINT32_C(0xAABBCCDD);cmd.payload_hash_actual=UINT32_C(0xAABBCCDD);make_nonce(cmd.nonce);return cmd;}
static void run_deterministic_tests(void){Gate gate;Command cmd;uint64_t now=UINT64_C(100000000000);memset(&gate,0,sizeof(gate));printf("\n========================================\nGATE ZERO DETERMINISTIC ADVERSARIAL TEST\n========================================\n\n");cmd=command_make(100,7,1,now);expect("bootstrap seq=1",gate_evaluate(&gate,&cmd,now),GATE_ACCEPT);cmd=command_make(100,7,2,now);expect("sequential seq=2",gate_evaluate(&gate,&cmd,now),GATE_ACCEPT);cmd=command_make(100,7,2,now);expect("replay seq=2",gate_evaluate(&gate,&cmd,now),GATE_SEQUENCE_REPLAY);cmd=command_make(100,7,4,now);expect("sequence gap seq=4",gate_evaluate(&gate,&cmd,now),GATE_SEQUENCE_GAP);cmd=command_make(100,7,3,now);expect("gap recovery seq=3",gate_evaluate(&gate,&cmd,now),GATE_ACCEPT);cmd=command_make(100,7,4,now);expect("retry seq=4",gate_evaluate(&gate,&cmd,now),GATE_ACCEPT);cmd=command_make(100,999,5,now);expect("wrong node",gate_evaluate(&gate,&cmd,now),GATE_WRONG_NODE);cmd=command_make(100,7,5,now);cmd.required_authority=AUTH_EMERGENCY;expect("insufficient authority",gate_evaluate(&gate,&cmd,now),GATE_AUTHORITY_INSUFFICIENT);cmd=command_make(100,7,5,now);cmd.command_type=CMD_SAFETY_DISABLE;expect("blocked safety bypass",gate_evaluate(&gate,&cmd,now),GATE_COMMAND_BLOCKED);cmd=command_make(100,7,5,now);cmd.expires_at_ns=now-1;expect("expired command",gate_evaluate(&gate,&cmd,now),GATE_EXPIRED);cmd=command_make(100,7,5,now);cmd.issued_at_ns=now+CLOCK_SKEW_NS+1;expect("future timestamp",gate_evaluate(&gate,&cmd,now),GATE_FUTURE_TIMESTAMP);cmd=command_make(100,7,5,now);cmd.payload_hash_actual^=1;expect("payload corruption",gate_evaluate(&gate,&cmd,now),GATE_PAYLOAD_CORRUPT);{Command first=command_make(100,7,5,now);Command second=command_make(100,7,6,now);
