f=open("gate0_crypto.c","a")
f.write("gate0_status_t gate0_aead_encrypt(gate0_aead_ctx_t *ctx,const uint8_t *pt,size_t pt_len,uint8_t *ct,uint8_t tag[16],uint8_t nonce[12]){\n")
f.write("if(!ctx||!pt||!ct||!tag||!nonce)return GATE0_ERR_BADKEY;\n")
f.write("uint64_t c=ctx->nonce_counter++;\n")
f.write("memcpy(nonce,&c,8);memset(nonce+8,0,4);\n")
f.write("crypto_aead_chacha20poly1305_ietf_encrypt_detached(ct,tag,NULL,pt,pt_len,NULL,0,NULL,nonce,ctx->key);\n")
f.write("return GATE0_OK;\n")
f.write("}\n")
f.write("gate0_status_t gate0_aead_decrypt(gate0_aead_ctx_t *ctx,const uint8_t *ct,size_t ct_len,const uint8_t tag[16],const uint8_t nonce[12],uint8_t *pt){\n")
f.write("if(!ctx||!ct||!pt||!tag||!nonce)return GATE0_ERR_BADKEY;\n")
f.write("if(crypto_aead_chacha20poly1305_ietf_decrypt_detached(pt,NULL,ct,ct_len,tag,NULL,0,nonce,ctx->key)!=0)return GATE0_ERR_DECRYPT;\n")
f.write("return GATE0_OK;\n")
f.write("}\n")
f.write("gate0_status_t gate0_sha256(const uint8_t *data,size_t len,uint8_t digest[32]){\n")
f.write("if(!data||!digest)return GATE0_ERR_BADKEY;\n")
f.write("crypto_hash_sha256(digest,data,len);\n")
f.write("return GATE0_OK;\n")
f.write("}\n")
f.close()
