f=open("gate0_crypto.c","a")
f.write("gate0_status_t gate0_x25519_keygen(gate0_x25519_keypair_t *kp){\n")
f.write("if(!kp)return GATE0_ERR_BADKEY;\n")
f.write("crypto_box_keypair(kp->pub,kp->priv);\n")
f.write("return GATE0_OK;\n")
f.write("}\n")
f.write("gate0_status_t gate0_x25519_dh(const gate0_x25519_keypair_t *local,const uint8_t remote[32],uint8_t secret[32]){\n")
f.write("if(!local||!remote||!secret)return GATE0_ERR_BADKEY;\n")
f.write("if(crypto_scalarmult(secret,local->priv,remote)!=0)return GATE0_ERR_BADKEY;\n")
f.write("return GATE0_OK;\n")
f.write("}\n")
f.write("gate0_status_t gate0_aead_init(gate0_aead_ctx_t *ctx,const uint8_t key[32]){\n")
f.write("if(!ctx||!key)return GATE0_ERR_BADKEY;\n")
f.write("memcpy(ctx->key,key,32);\n")
f.write("ctx->nonce_counter=0;\n")
f.write("return GATE0_OK;\n")
f.write("}\n")
f.close()
