f=open("gate0_crypto.c","w")
f.write("#include \"gate0_crypto.h\"\n")
f.write("#include <sodium.h>\n")
f.write("#include <string.h>\n")
f.write("#include <time.h>\n")
f.write("gate0_status_t gate0_ed25519_keygen(gate0_ed25519_keypair_t *kp){\n")
f.write("if(!kp)return GATE0_ERR_BADKEY;\n")
f.write("crypto_sign_ed25519_keypair(kp->pub,kp->priv);\n")
f.write("return GATE0_OK;\n")
f.write("}\n")
f.write("gate0_status_t gate0_ed25519_sign(const gate0_ed25519_keypair_t *kp,const uint8_t *msg,size_t len,uint8_t sig[64]){\n")
f.write("if(!kp||!msg||!sig)return GATE0_ERR_BADKEY;\n")
f.write("unsigned long long siglen;\n")
f.write("crypto_sign_ed25519_detached(sig,&siglen,msg,len,kp->priv);\n")
f.write("return GATE0_OK;\n")
f.write("}\n")
f.write("gate0_status_t gate0_ed25519_verify(const uint8_t pub[32],const uint8_t *msg,size_t len,const uint8_t sig[64]){\n")
f.write("if(!pub||!msg||!sig)return GATE0_ERR_BADKEY;\n")
f.write("if(crypto_sign_ed25519_verify_detached(sig,msg,len,pub)!=0)return GATE0_ERR_VERIFY;\n")
f.write("return GATE0_OK;\n")
f.write("}\n")
f.close()
