f=open("gate0_crypto.h","r")
c=f.read()
f.close()
c=c.replace("#endif\n","")
f=open("gate0_crypto.h","w")
f.write(c)
f.write("typedef struct {\n")
f.write("uint8_t pub[32];\n")
f.write("uint8_t priv[64];\n")
f.write("} gate0_ed25519_keypair_t;\n")
f.write("typedef struct {\n")
f.write("uint8_t pub[32];\n")
f.write("uint8_t priv[32];\n")
f.write("} gate0_x25519_keypair_t;\n")
f.write("typedef struct {\n")
f.write("uint8_t key[32];\n")
f.write("uint64_t nonce_counter;\n")
f.write("} gate0_aead_ctx_t;\n")
f.write("typedef struct {\n")
f.write("uint8_t prev_hash[32];\n")
f.write("uint64_t seq;\n")
f.write("uint64_t timestamp_us;\n")
f.write("uint8_t entry_hash[32];\n")
f.write("uint8_t chain_hash[32];\n")
f.write("} gate0_chain_link_t;\n")
f.write("#endif\n")
f.close()
