f=open("gate0_test.c","w")
f.write("#include \"gate0_crypto.h\"\n")
f.write("#include <sodium.h>\n")
f.write("#include <stdio.h>\n")
f.write("#include <string.h>\n")
f.write("int main(){\n")
f.write("if(sodium_init()<0){printf(\"sodium_init failed\\n\");return 1;}\n")
f.write("gate0_ed25519_keypair_t kp;\n")
f.write("gate0_ed25519_keygen(&kp);\n")
f.write("uint8_t msg[]=\"gate0 test message\";\n")
f.write("uint8_t sig[64];\n")
f.write("gate0_ed25519_sign(&kp,msg,sizeof(msg),sig);\n")
f.write("gate0_status_t r=gate0_ed25519_verify(kp.pub,msg,sizeof(msg),sig);\n")
f.write("if(r==GATE0_OK)printf(\"Ed25519 PASS\\n\");\n")
f.write("else printf(\"Ed25519 FAIL\\n\");\n")
f.write("return 0;\n")
f.write("}\n")
f.close()
