f=open("gate0_crypto.h","w")
f.write("#ifndef GATE0_CRYPTO_H\n")
f.write("#define GATE0_CRYPTO_H\n")
f.write("#include <stdint.h>\n")
f.write("#include <stddef.h>\n")
f.write("#define GATE0_SHA256_BYTES 32\n")
f.write("#define GATE0_ED25519_SIG_BYTES 64\n")
f.write("#define GATE0_CHACHA20_KEY_BYTES 32\n")
f.write("#define GATE0_CHACHA20_NONCE_BYTES 12\n")
f.write("#define GATE0_POLY1305_TAG_BYTES 16\n")
f.write("#endif\n")
f.close()
